POST http://localhost:8080/api/v1/usuario/register
Content-Type: application/json
Accept: application/json

{
    "name": "Luis",
    "lastName": "Sandoval",
    "email": "luisguti@gmail.com",
    "password": "m",
    "phone": "78544214",
    "address": "Achumani Huayllani",
    "carnet": "6794574"
}
