POST http://localhost:8080/api/v1/usuario/register
Content-Type: application/json
Accept: application/json

{
    "name": "Juan",
    "lastName": "Pérez",
    "email": "juanperez@example.com",
    "password": "password123",
    "phone": "123456789",
    "address": "123 Calle Principal",
    "carnet": "123456789"
}
