POST http://localhost:8080/api/v1/usuario/register
Content-Type: application/json
Accept: application/json

{
    "name": "Luis",
    "lastName": "Pérez",
    "email": "luisperez@example.com",
    "password": "pass1234",
    "phone": "78544214",
    "address": "987 Calle Principal",
    "carnet": "12345678"
}
