PUT http://localhost:8080/api/v1/usuario/1
Content-Type: application/json
Accept: application/json

{
    "name": "Fernandinha",
    "lastName": "Sandoval",
    "email": "ferguti@gmail.com",
    "password": "mfgs2003",
    "phone": "78544214",
    "address": "Achumani Huayllani",
    "carnet": "6794574"
}
