POST http://localhost:8080/api/v1/empresa/register
Content-Type: application/json
Accept: application/json

{
    "companyName": "Empresa 2",
    "typeAgreement": "CONTRATO",
    "requirements": "Ser hombre",
    "phone": "71544317",
    "email": "empresa2@gmail.com"
}