POST http://localhost:8080/api/v1/estudiantes/register
Content-Type: application/json
Accept: application/json

{
    "semester": "Segundo",
    "carrier": "Ingeniería Informática",
    "user": {
        "userId": 1,
        "name": "Nombre del Usuario",
        "lastName": "Apellido del Usuario",
        "email": "usuario@example.com",
        "password": "contraseña",
        "phone": "1234567890",
        "address": "Dirección del Usuario",
        "carnet": "Carnet del Usuario"
    },
    "typeUser": {
        "typeUserId": 1,
        "typeUser": "Tipo de Usuario"
    }
}