POST http://localhost:8080/api/v1/evento/1
Content-Type: application/json
Accept: application/json

{
    "tipoEvento": "evento jaja",
    "dateEvento": "2021-05-05T00:00",
    "descriptionEvento": "descripción del evento 1",
    "practicaRealizadaId": 1,
    "convocatoriaPracticaId": 1
}
